name: CI
on:
  push:
    branches:
      - main
  pull_request: true
env:
  FORCE_COLOR: 1
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.*
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: lint
        run: earthly --ci +lint
      - name: unittest
        run: earthly --ci +test